version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tynebrewdb
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db-data:
