name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose build

      - name: Run Containers for Testing
        run: docker compose up -d

      - name: Basic smoke test
        run: |
          sleep 15
          curl --fail http://localhost:8080 || exit 1

      - name: Stop containers
        run: docker compose down
