name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Wait for web to be ready
        run: |
          for i in {1..10}; do
            curl -s --head http://localhost:8080 | grep "200 OK" && break
            echo "Waiting for web..."
            sleep 3
          done

      - name: Run full PHP test suite
        run: docker compose exec web php /var/www/html/tests/full_test_suite.php

      - name: Stop containers
        run: docker compose down

      - name: Simulated Deployment
        run: echo "Deploying to staging environment."
