name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Wait for services to be ready
        run: sleep 15

      - name: Run full PHP test suite
        run: docker compose exec web php /var/www/html/tests/full_test_suite.php

      - name: Stop containers
        run: docker compose down
